/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TestMain */

#ifndef _Included_TestMain
#define _Included_TestMain
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TestMain
 * Method:    native_call
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_TestMain_native_1call
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
